### ISSUE TITLE
Replace the way we define C++ constants.

### ISSUE THREAD

**Issue by phuang1024** [phuang1024/piano_video#6]
`constexpr` is better than `#define` for constants because `constexpr` has a type.

Replace all `#define  ASDF  0.1` with `constexpr float ASDF = 0.1`.
Set the type based on your best judgement.

**Comment by eagleeye0** [comment]
Can I try to do this

**Comment by phuang1024** [comment]
No problem! Please fork the repository, make your changes, and make a pull request. Thanks for contributing!

**Comment by eagleeye0** [comment]
I dont know much about contributing. This is my first contribution to open source. Can you help me?
I have found one cpp file in the project which use define but I dont know how to resolve the issue.

**Comment by phuang1024** [comment]
The `cpp` files are mainly in `src/pvkernel/addons`. In there, look through all the sub-directories, and in some of the `.cpp` files, you will see some lines similar to `#define  VARIABLE  0.1234` at the top. Replace this line with `constexpr VARIABLE = 0.1234`.

For instructions on forking and pull requesting, see [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) on the GitHub docs.

Thanks!

**Comment by eagleeye0** [comment]
There I did it. Accept my pull request.
